config/routes.rb
Trazapp::Application.routes.draw do
  resources :tmp_actividades
  resources :tmp_proyectos
  resources :proyectos
  resources :usuarios
  resources :actividades
  resources :tareas

  root to: redirect('/login')

  scope controller: 'sessions' do
    get '/login', action: 'new', as: :login
    post '/login', action: 'create'
    match '/logout', action: 'destroy', as: :logout
  end

  match '/alumnos' => 'alumnos#index'
  match '/profesor' => 'profesores#index'

  match '/solicitudes' => 'tmp_proyectos#index', as: :solicitudes
  match '/proyectos' => 'proyectos#index', as: :proyectos


  match '/reportes' => 'reportes#index', as: :reportes
  match '/reporte-general' => 'reportes#reporte_general'

  scope '/configuraciones', controller: 'configuraciones' do
    match '/', action: 'index', as: :configuraciones
    post '/load_students', action: 'load_students'
    post '/load_structure', action: 'load_structure'
  end

  # match '/tmp_proyectos' => 'tmp_proyectos#create'
  # match '/tmp_proyectos/:id' => 'tmp_proyectos#update'

  scope 'solicitud', controller: 'tmp_proyectos' do
    match 'nueva', action: 'new', as: :nueva_solicitud
    match 'crear', action: 'create', as: :crear_solicitud
    match 'editar/:id', action: 'edit', as: :editar_solicitud
    match 'eliminar/:id', action: 'destroy', as: :eliminar_solicitud
    post 'modificar/:id', action: 'update', as: :modificar_solicitud
    match 'aprobar/:id', action: 'aprobar', as: :aprobar_solicitud
  end

  scope 'proyecto', controller: 'proyectos' do
    match 'nuevo', action: 'new'
    match 'editar/:id', action: 'edit', as: :editar_proyecto
    match 'eliminar/:id', action: 'destroy', as: :eliminar_proyecto
    scope 'actividad', controller: 'actividades' do
      post 'evaluar/:id', action: 'evaluar', as: :evaluar_actividad
      match ':id/:actividad', action: 'index'
      match 'eliminar/:id/:actividad', action: 'destroy'
      match ':id/nueva-tarea/:actividad', action: 'nueva_tarea'
    end
  end

  scope 'actividad', controller: 'actividades' do
    match 'editar/:id', action: 'edit', as: :editar_actividad
  end
end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  has_and_belongs_to_many :alumnos, class_name: 'Usuario', foreign_key: 'proyecto_id'
  has_many :actividades, class_name: 'Actividad'
  has_one :estructura, class_name: 'Estructura', foreign_key: 'id', primary_key: 'estructura_id'
  belongs_to :seccion

  delegate :rut, :nombre_completo, :correo_electronico, to: :alumnos
  validates_presence_of :nombre
  attr_accessible :estado, :fecha_cierre, :nombre, :estructura_id, :seccion_sigla, :descripcion
  before_save :establecer_cierre

  ESTADOS = {"Activo" => "activo", "Inactivo" => "inactivo", "Expirado" => "expirado", "Evaluado" => "evaluado"}

  def formatear_nombre
    self.nombre = self.nombre.titleize
  end

  def establecer_cierre
    self.fecha_cierre = 3.months.from_now
  end

  def codigo_acceso
    Digest::SHA1.hexdigest("TxOkysE#{id}uoYx#{created_at.strftime('%H%S')}MwpI7F8i9hOV")[3..11]
  end

  def progreso
    total = rand(1..100) #self.tareas.count
    completas = rand(1..total) #self.tareas.completas

    {completo: (completas*100/total).round, incompleto: total-completas}
  end

  def asignar_seccion
    unless self.seccion_sigla.nil?
      self.seccion = Seccion.where(sigla: seccion_sigla).first
    end
  end

  def seccion_sigla
    if self.seccion.present?
      self.seccion.sigla
    else
      @seccion_sigla
    end
  end

  def seccion_sigla=(sigla)
    unless sigla.nil?
      self.seccion = Seccion.where(sigla: sigla).first
      @seccion_sigla = sigla
    end
  end

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  def index
    @proyectos = Proyecto.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyectos }
    end
  end

  def show
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyecto }
    end
  end

  def new
    redirect_to controller: 'tmp_proyectos', action: 'new'
  end

  def edit
    @proyecto = Proyecto.find(params[:id])
    if @proyecto
      @actividades = @proyecto.actividades.order('created_at DESC')
      @alumnos = @proyecto.alumnos
      @complejidad = Actividad::Complejidad
    else
      flash[:error] = "Proyecto no encontrado"
      redirect_to '/activos'
    end
  end

  def create
    proyecto = Proyecto.create({nombre: params[:proyecto][:nombre]})

    if proyecto.id.present?
      users = 1
      until params["alumno_#{users}"].nil?
        alumno = params["alumno_#{users}"].merge({proyecto_id: proyecto.id, perfil: 'alumno'})
        users = (Usuario.create(alumno) ? users + 1 : 0)
      end

      actividades = 1
      until params["actividad_#{actividades}"].nil?
        actividad = params["actividad_#{actividades}"].merge({proyecto_id: proyecto.id})
        actividades = (Actividad.create(actividad) ? actividades + 1 : 0)
      end

      render text: 'OK' #devolver codigo de acceso
    else
      flash[:notice] = "ERROR!, No se pudo crear proyecto"
      redirect_to action: 'new'
    end
  end

  def update
    render text: "UPDATE!\n#{params.inspect}"
  end

  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper

  def proyecto_estado(estado)
    type = case estado
      when 'activo'   then 'success'
      when 'inactivo' then 'danger'
      when 'expirado' then 'warning'
      when 'evaluado' then 'primary'
      else
        'default'
      end
    raw("<span class='label label-#{type}'>#{estado.titleize}</span>")
  end

end

app/views/proyectos/_form_actividad.html.erb
<div class="row-fluid actividades">
  <div class="div1">Módulo</div>
  <div class="div2">Nombre/Funcionalidad</div>
  <div class="div3">Complejidad</div>
  <div class="div4">Revisión</div>
</div>

<% if Array(@actividades).any? %>
  <% @actividades.each_with_index do |actividad, i| %>
    <div class="row-fluid detalle <%= cycle('odd', 'even') -%>">
      <div class="div1">
        <%= text_field_tag "actividad_#{i+1}[modulo]", actividad.modulo, {class: 'text_field'} %>
      </div>
      <div class="div2">
        <%= text_field_tag "actividad_#{i+1}[funcionalidad]",actividad.funcionalidad, {class: 'text_field funcionalidad'} %>
      </div>
      <div class="div3">
        <%= select_tag "actividad_#{i+1}[complejidad]",options_for_select(@complejidad, actividad.complejidad), {include_blank: true, class: 'number_field complejidad'} %>
      </div>
      <div class="div4">
        <%= select_tag "actividad_#{i+1}[dia]", options_for_select(1..31,actividad.revision.day), {class: "fecha_dia"} %>
        <%= select_tag "actividad_#{i+1}[mes]", options_for_select(meses_helper,actividad.revision.month), {class: "fecha_mes"} %>
        <%= select_tag "actividad_#{i+1}[anio]", options_for_select(anio_helper,actividad.revision.year), {class: "fecha_anio"} %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row-fluid detalle">
    <div class="div1">
      <%= text_field_tag "actividad_1[modulo]",'', {class: 'text_field'} %>
    </div>
    <div class="div2">
      <%= text_field_tag "actividad_1[funcionalidad]",'', {class: 'text_field funcionalidad'} %>
    </div>
    <div class="div3">
      <%= select_tag "actividad_1[complejidad]",options_for_select(@complejidad), {include_blank: true, class: 'number_field complejidad'} %>
    </div>
    <div class="div4">
      <%= select_tag 'actividad_1[dia]', options_for_select(1..31,Time.now.day), {class: "fecha_dia"} %>
      <%= select_tag 'actividad_1[mes]', options_for_select(meses_helper,Time.now.month), {class: "fecha_mes"} %>
      <%= select_tag 'actividad_1[anio]', options_for_select(anio_helper,Time.now.year), {class: "fecha_anio"} %>
    </div>
  </div>
<% end %>

<div class="control_actividades">
  <a href="#" id="nueva_actividad"><span class="button add"></span></a>
  <a href="#" id="eliminar_actividad"><span class="button delete"></span></a>
</div>

app/views/proyectos/_form_actividad2.html.erb
<div class="contenedor_interno">
  <h3>Actividades</h3>
  <div id="listado_tareas">
    <div class="row listado_tareas">
    <% if Array(@actividades).any? %>
      <% @actividades.each_with_index do |actividad, i| %>
        <div class="tarea header <%= cycle('odd', 'even') %> <%= 'description-header' if i > 0 %> <%= 'last-child' if i == @actividades.length-1 %>">
          <div class="columns col-md-1"> <strong>#</strong></div>
          <div class="columns col-md-4"> <strong>Nombre</strong></div>
          <div class="columns col-md-3"> <strong>Progreso</strong></div>
          <div class="columns col-md-2"> <strong>Acciones</strong></div>
        </div>
        <div class="tarea <%= cycle('odd', 'even') -%>">
          <div class="columns col-md-1"> <%= i+1 %> </div>
          <div class="columns col-md-4">
            <%= label_tag "actividad_#{i+1}[nombre]", actividad.nombre, {class: 'text_field'} %>
          </div>
          <div class="columns col-md-3">
            <div class="form-group">
            <div class="progress">
              <% act = @proyecto.progreso[:completo]%>
              <div class="progress-bar progress-striped active"  role="progressbar" aria-valuenow="<%= act %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= act %>%">
                <span class="sr-only"><%= act %> %</span>
              </div>
            </div>
          </div>
          </div>
          <div class="columns col-md-2">
            <%= link_to "Ver/Editar", editar_actividad_path(actividad.id), {class: "btn btn-xs btn-info"} %>
            <%= link_to 'Eliminar', url_to_actividad(actividad, '/eliminar') , data: { confirm: '¿Estás seguro?'},
                        class: 'btn btn-xs btn-danger' %>
          </div>
        </div>
      <% end %>
    <% else %>
      NUEVA ACT! (In Progress...)
      <a href="#" id="nueva_actividad"><span class="button add"></span></a>
    <% end %>
    </div>
  </div>
</div>
<!-- <div class="control_actividades">
  <a href="#" id="nueva_actividad"><span class="button add"></span></a>
  <a href="#" id="eliminar_actividad"><span class="button delete"></span></a>
</div>
 -->

app/views/proyectos/_project_info.erb
<div class="container">
  <div class="project-name">
    <h4>Nombre del Proyecto</h4>
    <div class="row">
      <div class="col-md-4"> <%= @proyecto.nombre %> </div>
    </div>
  </div>
  <br>
  <div class="students-list">
    <h4>Alumnos(s)</h4>
    <div class="row">
      <div class="col-md-1"><b>#</b></div>
      <div class="col-md-2"><b>Rut</b></div>
      <div class="col-md-3"><b>Nombre</b></div>
      <div class="col-md-3"><b>Correo electrónico</b></div>
    </div>
    <% @alumnos.each_with_index do |alumno, i| %>
    <div class="row">
      <div class="col-md-1"> <%= i+1 %> </div>
      <div class="col-md-2"> <%= alumno.rut %> </div>
      <div class="col-md-3"> <%= alumno.nombre_completo.titleize %> </div>
      <div class="col-md-3"> <%= alumno.correo_electronico %> </div>
    </div>
    <% end %>
  </div>
</div>

app/views/proyectos/edit.html.erb
<%= content_for :name, 'Seguimiento de Proyecto' %>
<%= content_for :description, "Número ##{@proyecto.id}" %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa-file"></i> Proyectos / <i class="fa fa-fw fa-align-left"></i> Seguimiento') %>

<div class="row-fluid">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-info-circle"></i> Información General</h3>
    </div>
    <div class="panel-body">
        <%= render partial: 'project_info' %>
    </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-tasks"></i> Actividades</h3>
    </div>
    <div class="panel-body">
      <%= render partial: 'form_actividad2' %>
    </div>
  </div>

  <div class="well well-small pull-left">
    <%= link_to 'Volver', proyectos_url, :class => 'btn btn-primary' %>
  </div>

</div>

<script type="text/javascript">
  $(function(){
    TmpProyecto.init();
  });
</script>

app/views/proyectos/index.html.erb
<%- model_class = Proyecto -%>
<%= content_for :name, 'Proyectos' %>
<%= content_for :description, 'Listado completo' %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa-file"></i> Proyectos') %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Estado</th>
      <th>Fecha creación</th>
      <th>Fecha cierre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @proyectos.each_with_index do |proyecto, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= proyecto.nombre %></td>
        <td><%= proyecto_estado(proyecto.estado) %></td>
        <td><%= proyecto.created_at.strftime('%d/%m/%Y - %H:%M:%S') %></td>
        <td><%= proyecto.fecha_cierre.strftime('%d/%m/%Y') %></td>
        <td>
          <%= link_to "Ver/Editar", editar_proyecto_path(proyecto.id), {class: "btn btn-primary"} %>
          <%= link_to 'Eliminar', eliminar_proyecto_path(proyecto.id) , data: { confirm: '¿Estás seguro?'}, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="well well-small pull-right">
  <%= link_to 'Nuevo', '/proyecto/nuevo', :class => 'btn btn-primary' %>
</div>

<script>
  $(function(){
    TmpProyecto.profesor();
  });
</script>

app/views/proyectos/new.html.erb
<%- model_class = TmpProyecto -%>
<div class="container">
  <div class="alert hide fade in out alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>OK</strong> Registros agregados exitosamente
  </div>
  <div class="page-header">
    <h1>Inscribir Proyecto</h1>
  </div>
  <div class="forms_proyecto">
    <%= render partial: 'form' %>
  </div>

  <div class="form-actions-override">
    <button id="inscribir" type="button" class="btn btn-primary">Inscribir</button>
    <%= link_to t('.cancel', :default => 'Cancelar'),
                tmp_proyectos_path, :class => 'btn' %>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    TmpProyecto.init();
  });
</script>

app/views/proyectos/show.html.erb
<%- model_class = Proyecto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @tmp_proyecto.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado) %>:</strong></dt>
  <dd><%= @tmp_proyecto.estado %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tmp_proyectos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tmp_proyecto_path(@tmp_proyecto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tmp_proyecto_path(@tmp_proyecto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/proyectos/tabled_edit.html.erb
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Módulo</th>
      <th>Nombre/Funcionalidad</th>
      <th>Complejidad</th>
      <th>Revisión</th>
    </tr>
  </thead>
  <tbody class="actividades_body">
    <% if Array(@actividades).any? %>
      <% @actividades.each_with_index do |actividad, i| %>
        <tr class="actividades_field">
          <td><%= text_field_tag "actividad_#{i+1}[modulo]", actividad.modulo, {class: 'text_field'} %></td>
          <td><%= text_field_tag "actividad_#{i+1}[funcionalidad]",actividad.funcionalidad, {class: 'text_field funcionalidad'} %></td>
          <td><%= select_tag "actividad_#{i+1}[complejidad]",options_for_select(@complejidad, actividad.complejidad), {include_blank: true, class: 'number_field complejidad'} %></td>
          <td>
            <%= select_tag "actividad_#{i+1}[dia]", options_for_select(1..31,actividad.revision.day), {class: "fecha_dia"} %>
            <%= select_tag "actividad_#{i+1}[mes]", options_for_select(meses_helper,actividad.revision.month), {class: "fecha_mes"} %>
            <%= select_tag "actividad_#{i+1}[anio]", options_for_select(anio_helper,actividad.revision.year), {class: "fecha_anio"} %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr class="actividades_field">
        <td><%= text_field_tag "actividad_1[modulo]",'', {class: 'text_field'} %></td>
        <td><%= text_field_tag "actividad_1[funcionalidad]",'', {class: 'text_field funcionalidad'} %></td>
        <td><%= select_tag "actividad_1[complejidad]",options_for_select(@complejidad), {include_blank: true, class: 'number_field complejidad'} %></td>
        <td>
          <%= select_tag 'actividad_1[dia]', options_for_select(1..31,Time.now.day), {class: "fecha_dia"} %>
          <%= select_tag 'actividad_1[mes]', options_for_select(meses_helper,Time.now.month), {class: "fecha_mes"} %>
          <%= select_tag 'actividad_1[anio]', options_for_select(anio_helper,Time.now.year), {class: "fecha_anio"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>