config/routes.rb
Trazapp::Application.routes.draw do
  resources :tmp_actividades
  resources :tmp_proyectos
  resources :proyectos
  resources :usuarios
  resources :actividades
  resources :tareas

  root to: redirect('/login')

  scope controller: 'sessions' do
    get '/login', action: 'new', as: :login
    post '/login', action: 'create'
    match '/logout', action: 'destroy', as: :logout
  end

  match '/alumnos' => 'alumnos#index'
  match '/profesor' => 'profesores#index'

  match '/solicitudes' => 'tmp_proyectos#index', as: :solicitudes
  match '/proyectos' => 'proyectos#index', as: :proyectos


  match '/reportes' => 'reportes#index', as: :reportes
  match '/reporte-general' => 'reportes#reporte_general'

  scope '/configuraciones', controller: 'configuraciones' do
    match '/', action: 'index', as: :configuraciones
    post '/load_students', action: 'load_students'
    post '/load_structure', action: 'load_structure'
  end

  # match '/tmp_proyectos' => 'tmp_proyectos#create'
  # match '/tmp_proyectos/:id' => 'tmp_proyectos#update'

  scope 'solicitud', controller: 'tmp_proyectos' do
    match 'nueva', action: 'new', as: :nueva_solicitud
    match 'crear', action: 'create', as: :crear_solicitud
    match 'editar/:id', action: 'edit', as: :editar_solicitud
    match 'eliminar/:id', action: 'destroy', as: :eliminar_solicitud
    post 'modificar/:id', action: 'update', as: :modificar_solicitud
    match 'aprobar/:id', action: 'aprobar', as: :aprobar_solicitud
  end

  scope 'proyecto', controller: 'proyectos' do
    match 'nuevo', action: 'new'
    match 'editar/:id', action: 'edit', as: :editar_proyecto
    match 'eliminar/:id', action: 'destroy', as: :eliminar_proyecto
    scope 'actividad', controller: 'actividades' do
      post 'evaluar/:id', action: 'evaluar', as: :evaluar_actividad
      match ':id/:actividad', action: 'index'
      match 'eliminar/:id/:actividad', action: 'destroy'
      match ':id/nueva-tarea/:actividad', action: 'nueva_tarea'
    end
  end

  scope 'actividad', controller: 'actividades' do
    match 'editar/:id', action: 'edit', as: :editar_actividad
  end
end

app/models/tmp_proyecto.rb
class TmpProyecto < ActiveRecord::Base
  belongs_to :seccion
  has_and_belongs_to_many :alumnos, class_name: 'Usuario', foreign_key: 'tmp_proyecto_id'

  attr_accessible :estado, :nombre, :descripcion, :seccion_id, :seccion_sigla, :estructura_id
  delegate :rut, :nombre_completo, :correo_electronico, to: :alumnos

  attr_accessor :estructura_id

  validates_presence_of :nombre, :descripcion, :seccion

  before_create :expirar
  before_save :formatear_nombre

  ESTADOS = %w(aprobado pendiente rechazado)

  def formatear_nombre
    self.nombre = self.nombre.titleize
  end

  def codigo_acceso
    Digest::SHA1.hexdigest("RxO39kysE#{id}uoYx#{created_at.strftime('%H%S')}LwQ4r7Di9hOV")[2..10]
  end

  def cantidad_actividades
    self.actividades.count
  end

  def evaluacion
    #Must be deleted after Bug Fix on classes and model name
    rand(1.0..7.0).round(1)
  end

  def expirar
    self.fecha_expiracion = Time.now + 15.days
  end

  def asignar_seccion
    unless self.seccion_sigla.nil?
      self.seccion = Seccion.where(sigla: seccion_sigla).first
    end
  end

  def seccion_sigla
    if self.seccion.present?
      self.seccion.sigla
    else
      @seccion_sigla
    end
  end

  def seccion_sigla=(sigla)
    unless sigla.nil?
      self.seccion = Seccion.where(sigla: sigla).first
      @seccion_sigla = sigla
    end
  end

  def pendiente?
    self.estado == 'pendiente'
  end

end

app/controllers/tmp_proyectos_controller.rb
class TmpProyectosController < ApplicationController

  def index
    @tmp_proyectos = TmpProyecto.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tmp_proyectos }
    end
  end

  def show
    @tmp_proyecto = TmpProyecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tmp_proyecto }
    end
  end

  def new
    @tmp_proyecto = TmpProyecto.new
    variables_comunes
  end

  def edit
    @tmp_proyecto = TmpProyecto.find(params[:id])
    if @tmp_proyecto
      variables_comunes
      @estructuras = Estructura.for_select
      @seccion = @tmp_proyecto.seccion
      @alumnos_solicitud = @tmp_proyecto.alumnos
      @alumnos_seccion = (@seccion.usuarios - @alumnos_solicitud).map{|a| [a.nombre_completo, a.id]}
      render :edit
    else
      flash[:error] = "Proyecto no encontrado"
      redirect_to solicitudes_url
    end
  end

  def create
    @solicitud = TmpProyecto.create(params[:tmp_proyecto])
    guardar_solicitud
  end

  def update
    @solicitud = TmpProyecto.find(params[:id])
    @solicitud.update_attributes(params[:tmp_proyecto])
    guardar_solicitud
  end

  def destroy
    @tmp_proyecto = TmpProyecto.find(params[:id])
    @tmp_proyecto.destroy

    respond_to do |format|
      format.html { redirect_to '/solicitudes' }
      format.json { head :no_content }
    end
  end

  def aprobar
    if request.post?
      proyecto = Proyecto.create(params[:tmp_proyecto])
      if proyecto.errors.empty?
        lista = params[:lista_alumnos].split(',')
        proyecto.alumnos = Usuario.where(id: lista)
        actividades = proyecto.estructura.json
        actividades.keys.each do |key|
          if actividades[key].is_a?(String)
            Actividad.create(
              proyecto_id: proyecto.id,
              nombre: key,
              puntos: actividades[key].to_i,
              progreso: 0,
              estado: 'incompleta',
              revision: Time.now + 1.month
              )
          else
            puntos = 0
            actividad = Actividad.create(
              proyecto_id: proyecto.id,
              nombre: key,
              puntos: puntos,
              progreso: 0,
              estado: 'incompleta',
              revision: Time.now + 1.month
              )
            actividades[key].keys.each do |tarea_key|
              Tarea.create(
                actividad_id: actividad.id,
                nombre: tarea_key,
                puntos: actividades[key][tarea_key].to_i,
                estado: 'incompleta',
                revision: Time.now + 1.month
                )
              puntos += actividades[key][tarea_key].to_i
            end
            actividad.update_attribute(:puntos, puntos)
          end
        end
        flash[:notice] = "Proyecto #{proyecto.nombre} activado exitosamente"
        redirect_to proyectos_url
      else
        flash[:error] = "Error al aprobar/crear nuevo Proyecto"
        redirect_to solicitudes_url
      end
    else
      redirect_to editar_solicitud_url(params[:id])
    end
  end

  private

    def variables_comunes
      @alumnos = Seccion.to_hash.to_json
      @secciones = JSON.parse(@alumnos).keys
      @alumnos_seccion = []
      @alumnos_solicitud = []
    end

    def guardar_solicitud
      lista = params[:lista_alumnos].split(',')
      if @solicitud.errors.empty?
        @solicitud.alumnos = Usuario.where(id: lista)
        redirect_to(action: 'show', id: @solicitud.id)
      else
        flash[:error] = "Los datos fueron ingresados Incorrectamente"
        redirect_to(action: 'new')
      end
    end

end

app/helpers/tmp_proyectos_helper.rb
module TmpProyectosHelper

  def labeled_estado(estado)
    type = case estado
      when 'aprobado'    then 'success'
      when 'rechazado'  then 'danger'
      when 'pendiente'  then 'warning'
      else
        'default'
      end
    raw("<span class='label label-#{type}'>#{estado.titleize}</span>")
  end

end

app/views/tmp_proyectos/_form.html.erb
<%= form_for @tmp_proyecto, url: action, html: { method: 'POST', class: 'form-horizontal new-proyecto' } do |f| %>
  <div class="control-group">
    <%= label_tag '', 'Nombre del proyecto', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls alumnos">
      <div class="alumnos-container">
        <div class="selectores">
          <%= label_tag '', 'Secciones', class: 'control-label' %>
          <%= f.select :seccion_sigla, options_for_select(@secciones), {prompt: 'Secciones'}, {class: 'form-control'} %>
          <%= f.label 'Alumno(s)', class: 'control-label' %>
          <%= select_tag :alumnos, options_for_select(@alumnos_seccion), {class: 'form-control students-list', prompt: 'Seleccione alumno'} %>
          <br>
          <%= button_tag 'Agregar', class: 'btn btn-success add'%>
        </div>
        <div class="seleccionados">
          <div class="lista">
            <% @alumnos_solicitud.each do |alumno| %>
              <span><%= alumno.nombre_completo %><span class='delete-student' data-id=<%= alumno.id %>>X</span></span>
            <% end %>
          </div>
          <%= hidden_field_tag :lista_alumnos %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="control-group">
    <%= f.label :descripcion, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :descripcion, {class: 'form-control', rows: '3', maxlength: '350'} %>
    </div>
  </div>

  <% if editar && (can? :aprobar, TmpProyecto) %>
    <br><br>
    <div class="control-group">
      <%= label_tag '', 'Seleccione Estructura de Evaluación', class: 'control-label' %>
      <%= f.select :estructura_id, options_for_select(@estructuras) ,{prompt: 'Estructuras'},{class: 'form-control'} %>
    </div>
  <% end %>
<% end %>

<%= hidden_field_tag :alumnos_json, @alumnos %>

app/views/tmp_proyectos/edit.html.erb
<%- model_class = TmpProyecto -%>
<%= content_for :name, "Modificar Solicitud" %>
<%= content_for :description, "Número ##{@tmp_proyecto.id}" %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa-edit"></i> Solicitudes / <i class="fa fa-fw fa-file"></i> Resultado ') %>

<div class="container">
  <div class="alert hide fade in out alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>OK</strong> Registros modificados exitosamente
  </div>
  <div class="forms_proyecto">
    <%= render partial: 'form', locals: {action: modificar_solicitud_path, editar: true} %>
  </div>

  <div class="form-actions-override">
    <button id="inscribir" type="button" class="btn btn-primary">Guardar</button>
    <% if (can? :aprobar, TmpProyecto) && @tmp_proyecto.pendiente? %>
      <%= link_to 'Aprobar', aprobar_solicitud_path(@tmp_proyecto.id), {class: 'btn btn-success aprobar'} %>
    <% end %>
    <%= link_to "Cancelar", solicitudes_path, class: 'btn btn-danger' %>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    TmpProyecto.init();
  });
</script>

app/views/tmp_proyectos/index.html.erb
<%= content_for :name, 'Solicitudes' %>
<%= content_for :description, 'Listado de Pendientes' %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa-edit"></i> Solicitudes ') %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Estado</th>
      <th>Fecha creación</th>
      <th>Fecha expiración</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @tmp_proyectos.each_with_index do |solicitud, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= solicitud.nombre %></td>
        <td><%= labeled_estado(solicitud.estado) %></td>
        <td><%= solicitud.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= solicitud.fecha_expiracion.try(:strftime, '%d/%m/%Y') %></td>
        <td>
          <%= link_to "Ver/Editar", editar_solicitud_path(id: solicitud.id), {class: "btn btn-primary"} %>
          <%= link_to 'Eliminar', eliminar_solicitud_path(id: solicitud.id),
                      data: {confirm: '¿Estás seguro?'}, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="well well-small pull-right">
  <%= link_to 'Nuevo', nueva_solicitud_path, class: 'btn btn-primary' %>
</div>

<script>
  $(function() {
    TmpProyecto.profesor();
  });
</script>

app/views/tmp_proyectos/new.html.erb
<%- model_class = TmpProyecto -%>
<div class="container">
  <div class="page-header">
    <h1>Inscribir Proyecto</h1>
  </div>
  <div class="forms_proyecto">
    <%= render partial: 'form', locals: {action: crear_solicitud_path, editar: false} %>
  </div>

  <div class="form-actions-override">
    <button id="inscribir" type="button" class="btn btn-primary">Inscribir</button>
    <%= link_to 'Cancelar', solicitudes_path, class: 'btn btn-danger' %>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    TmpProyecto.init();
  });
</script>

app/views/tmp_proyectos/show.html.erb
<%- model_class = TmpProyecto -%>


<div class="well">
  <div>
    <p>Has registrado el proyecto exitosamente.</p>
    <p>Tu solicitud tiene número #<%= @tmp_proyecto.id %></p>
    <p>y será notificada al Profesor <%= @profesor.nombre_completo %></p>
    <p>Estado actual: <%= @tmp_proyecto.estado %></p>
  </div>
</div>

<div class="form-actions">
  <%= link_to 'Click para ver solicitudes.', tmp_proyectos_path, :class => 'btn'  %>
</div>