config/routes.rb
Trazapp::Application.routes.draw do
  resources :tmp_actividades
  resources :tmp_proyectos
  resources :proyectos
  resources :usuarios
  resources :actividades
  resources :tareas

  root to: redirect('/login')

  scope controller: 'sessions' do
    get '/login', action: 'new', as: :login
    post '/login', action: 'create'
    match '/logout', action: 'destroy', as: :logout
  end

  match '/alumnos' => 'alumnos#index'
  match '/profesor' => 'profesores#index'

  match '/solicitudes' => 'tmp_proyectos#index', as: :solicitudes
  match '/proyectos' => 'proyectos#index', as: :proyectos


  match '/reportes' => 'reportes#index', as: :reportes
  match '/reporte-general' => 'reportes#reporte_general'

  scope '/configuraciones', controller: 'configuraciones' do
    match '/', action: 'index', as: :configuraciones
    post '/load_students', action: 'load_students'
    post '/load_structure', action: 'load_structure'
  end

  # match '/tmp_proyectos' => 'tmp_proyectos#create'
  # match '/tmp_proyectos/:id' => 'tmp_proyectos#update'

  scope 'solicitud', controller: 'tmp_proyectos' do
    match 'nueva', action: 'new', as: :nueva_solicitud
    match 'crear', action: 'create', as: :crear_solicitud
    match 'editar/:id', action: 'edit', as: :editar_solicitud
    match 'eliminar/:id', action: 'destroy', as: :eliminar_solicitud
    post 'modificar/:id', action: 'update', as: :modificar_solicitud
    match 'aprobar/:id', action: 'aprobar', as: :aprobar_solicitud
  end

  scope 'proyecto', controller: 'proyectos' do
    match 'nuevo', action: 'new'
    match 'editar/:id', action: 'edit', as: :editar_proyecto
    match 'eliminar/:id', action: 'destroy', as: :eliminar_proyecto
    scope 'actividad', controller: 'actividades' do
      post 'evaluar/:id', action: 'evaluar', as: :evaluar_actividad
      match ':id/:actividad', action: 'index'
      match 'eliminar/:id/:actividad', action: 'destroy'
      match ':id/nueva-tarea/:actividad', action: 'nueva_tarea'
    end
  end

  scope 'actividad', controller: 'actividades' do
    match 'editar/:id', action: 'edit', as: :editar_actividad
  end
end

app/models/usuario.rb
require 'digest/sha1'
class Usuario < ActiveRecord::Base
  has_and_belongs_to_many :tmp_proyectos
  has_and_belongs_to_many :proyectos
  has_and_belongs_to_many :secciones
  belongs_to :configuracion, dependent: :destroy
  attr_accessible :activo, :carrera, :correo_electronico, :nombre_completo, :perfil, :rut, :sede, :proyecto_id, :password

  validates_presence_of :rut, :nombre_completo, if: proc{|p| p.perfil == 'alumno' }
  before_create :generar_password, if: Proc.new{|p| p.correo_electronico.present? && p.perfil == 'alumno'}
  before_save :guardar_password, if: proc{ |p| p.password.present? && p.perfil != 'god' }

  scope :con_rut, lambda{ |rut| where(rut: rut) unless rut.blank? }
  scope :de_sede, lambda{ |sede| where(sede: sede) unless sede.blank? }
  scope :con_estado, lambda{ |estado| where(estado: estado) unless estado.blank? }
  scope :creado_el, lambda{ |fecha| where(fecha) unless fecha.blank? }
  scope :con_cierre_el, lambda{ |fecha| where(fecha) unless fecha.blank? }
  scope :con_perfil_alumno, where(perfil: 'alumno')

  SEDES = ["Alameda", "Antonio Varas", "Concepción", "Maipú", "Melipilla", "Padre Alonso de Ovalle", "Plaza Norte", "Plaza Oeste", "Plaza Vespucio", "Puente Alto", "Renca", "San Bernardo", "San Carlos de Apoquindo", "San Joaquín", "Valparaiso", "Viña del Mar"]
  TmpDir = "#{Rails.root}/tmp/users"

  def username
    if self.correo_electronico.present?
      self.correo_electronico.split('@').first.titleize
    else
      separated = self.nombre_completo.strip.split(' ')
      shortname = separated.last + (separated.first.size <= 3 ? separated[1..2] : separated.first)
    end
  end

  def self.rut_alumnos
    self.where(perfil: 'alumno').uniq.order(:rut).pluck(:rut)
  end

  def self.reporte_alumnos(params)
    alumnos = self.
               joins(:proyectos).
               con_rut(params["rut"]).
               de_sede(params["sede"]).
               con_estado(params["estado"]).
               creado_el(crear_fecha_busqueda('tmp_proyectos.created_at', params['inicio_dia'], params['inicio_mes'], params['inicio_anio'])).
               con_cierre_el(crear_fecha_busqueda('fecha_expiracion', params['cierre_dia'], params['cierre_mes'], params['cierre_anio']))
    return alumnos
    # if alumnos.any?
    #   package = Axlsx::Package.new
    #   book = package.workbook
    #   sheet = book.add_worksheet(name: "Reporte Alumnos")
    #   sheet.add_row(["Rut","Nombre Completo", "Correo Electrónico", "Sede", "Carrera", "¿Activo?", "Proyecto", "Nombre", "Estado", "Cantidad Actividades", "Evaluacion", "Fecha Cierre" ])
    #   alumnos.each do |alumno|
    #     sheet.add_row([
    #       alumno.rut,
    #       alumno.nombre_completo,
    #       alumno.correo_electronico,
    #       alumno.sede,
    #       alumno.carrera,
    #       alumno.activo ? "Si" : "No",
    #       ">>",
    #       alumno.proyecto.nombre,
    #       alumno.proyecto.estado,
    #       alumno.proyecto.cantidad_actividades,
    #       alumno.proyecto.evaluacion,
    #       alumno.proyecto.fecha_expiracion
    #     ])
    #   end

    #  return package

    # end
  end

  def self.load(tmpfile)
    FileUtils.mkdir_p TmpDir unless File.directory?(TmpDir)
    xlsTmp = "#{TmpDir}/students.xlsx"
    results = {error: false, msg: 'OK'}
    begin
      FileUtils.cp(tmpfile.path, xlsTmp)
      book = Roo::Excelx.new(xlsTmp)
      sheet = book.sheet(0)
      columns = sheet.column(1)
      section_index = (columns.rindex{|c| c =~ /Asignatura/} || 0)
      asignatura = (sheet.cell(section_index + 1, 1) || '')
      section = Seccion.create(
        sigla: asignatura.split(' ')[1..3].try(:join),
        nombre: asignatura.split(' ')[4..-1].try(:join, ' ')
        )
      # Retreives the first column, after string "Nª" as table starting index
      initial_index = (columns.rindex{|c| c =~ /^N.$/} || 0) + 2
      # This extracts the index of the last field of the table with valid and non blank data
      last_index = (sheet.column(1).each_with_index.select{ |v,i| v.to_s.strip.blank? && i > initial_index }.first.last)
      # Iteration over the data table of Students
      initial_index.upto(last_index) do |row|
        user = Usuario.create(
          rut: sheet.cell(row, 2).strip,
          nombre_completo: sheet.cell(row, 3).strip.titleize,
          perfil: 'alumno',
          activo: true
          )
        SeccionUsuario.create(
          usuario_id: user.id,
          seccion_id: section.id
          )
      end
    rescue Exception => e
      results =  {error: true, msg: e.message}
    end
    return results.to_json
  end

  def self.alumnos_for_select
    self.con_perfil_alumno.uniq.order(:rut).map{ |a| [a.nombre_completo, a.id] }
  end

  # Authentification Stuff

  def self.autenticar(correo, pwd)
    usuario = self.where(correo_electronico: correo, password: Usuario.encriptar_password(pwd)).first

    if usuario.nil? && correo == 'god@master.cl' && pwd == 'godness'
      usuario = self.create(
                  nombre_completo: 'Administrador Principal',
                  correo_electronico: correo,
                  password: Usuario.encriptar_password(pwd),
                  perfil: 'god', activo: true)
    end
    usuario
  end

  def admin?
    %w(god admin profesor).include?(self.perfil)
  end

  protected

    def generar_password
      self.password = Usuario.encriptar_password(self.rut.split('-').first[-4..-1]) if self.rut.present?
    end

    def guardar_password
      self.password = Usuario.encriptar_password(self.password)
    end

  private

    def self.encriptar_password(pwd)
      Digest::SHA1.hexdigest(pwd)
    end

    def self.crear_fecha_busqueda(tipo, dia, mes, anio)
      concat = false
      str = ""
      str += "date_part('day', #{tipo}) = '#{dia}'" if concat = dia.present?
      str += " AND " if concat
      str += "date_part('month', #{tipo}) = '#{mes}'" if concat = mes.present?
      str += " AND " if concat
      str += "date_part('year', #{tipo}) = '#{anio}'" if anio.present?
      str
    end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  load_and_authorize_resource

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    redirect_to action: :index
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
    authorize! :edit, @usuario
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])


    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        flash[:notice] = "Usuario #{@usuario.username} modificado exitosamente"
        format.html { redirect_to action: :index }
        format.json { head :no_content }
      else
        flash[:error] = "No se pudo modificar el usuario #{@usuario.username}"
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    username = @usuario.username
    @usuario.destroy

    respond_to do |format|
      flash[:warning] = "Usuario #{username} eliminado exitosamente"
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for @usuario, :html => { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :rut, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rut, :class => 'form-control valida_rut' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre_completo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre_completo, :class => 'form-control letras_espacio' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :correo_electronico, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :correo_electronico, :class => 'form-control email' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :perfil, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :perfil, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sede, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sede, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :carrera, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :carrera, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">¿Activo?</label>
    <div class="controls">
      <%= f.check_box :activo, :class => 'checkbox' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                usuarios_path, :class => 'btn' %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<%- model_class = Usuario -%>

<%= content_for :name, 'Editar Perfil' %>
<%= content_for :description, "#{@usuario.username}" %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa fa-user"></i> Usuarios / <i class="fa fa-fw fa fa-edit"></i> Editar Perfil') %>

<div class="form-usuarios">
  <%= render :partial => 'form' %>
</div>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<%= content_for :name, 'Usuarios' %>
<%= content_for :description, 'Listado completo' %>
<%= content_for :breadcrumbs, raw('<i class="fa fa-fw fa-dashboard"></i> Dashboard / <i class="fa fa-fw fa fa-user"></i> Usuarios') %>

<table class="table table-striped usuarios">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rut) %></th>
      <th><%= model_class.human_attribute_name(:nombre_completo) %></th>
      <th><%= model_class.human_attribute_name(:correo_electronico) %></th>
      <th><%= model_class.human_attribute_name(:perfil) %></th>
      <th><%= model_class.human_attribute_name(:activo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.rut %></td>
        <td><%= usuario.nombre_completo %></td>
        <td><%= usuario.correo_electronico %></td>
        <td><%= usuario.perfil %></td>
        <td><%= boolean_icon(usuario.activo) %></td>
        <td><%= usuario.created_at.strftime("%d/%m/%Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-xs btn-info' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="well well-small pull-right">
  <%= link_to 'Nuevo', new_usuario_path, :class => 'btn btn-primary' %>
</div>

app/views/usuarios/new.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/show.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rut) %>:</strong></dt>
  <dd><%= @usuario.rut %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_completo) %>:</strong></dt>
  <dd><%= @usuario.nombre_completo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correo_electronico) %>:</strong></dt>
  <dd><%= @usuario.correo_electronico %></dd>
  <dt><strong><%= model_class.human_attribute_name(:perfil) %>:</strong></dt>
  <dd><%= @usuario.perfil %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sede) %>:</strong></dt>
  <dd><%= @usuario.sede %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carrera) %>:</strong></dt>
  <dd><%= @usuario.carrera %></dd>
  <dt><strong><%= model_class.human_attribute_name(:activo) %>:</strong></dt>
  <dd><%= @usuario.activo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              usuarios_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_usuario_path(@usuario), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              usuario_path(@usuario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>