config/routes.rb
Trazapp::Application.routes.draw do
  resources :tmp_actividades
  resources :tmp_proyectos
  resources :proyectos
  resources :usuarios
  resources :actividades
  resources :tareas

  root to: redirect('/login')

  scope controller: 'sessions' do
    get '/login', action: 'new', as: :login
    post '/login', action: 'create'
    match '/logout', action: 'destroy', as: :logout
  end

  match '/alumnos' => 'alumnos#index'
  match '/profesor' => 'profesores#index'

  match '/solicitudes' => 'tmp_proyectos#index', as: :solicitudes
  match '/proyectos' => 'proyectos#index', as: :proyectos


  match '/reportes' => 'reportes#index', as: :reportes
  match '/reporte-general' => 'reportes#reporte_general'

  scope '/configuraciones', controller: 'configuraciones' do
    match '/', action: 'index', as: :configuraciones
    post '/load_students', action: 'load_students'
    post '/load_structure', action: 'load_structure'
  end

  # match '/tmp_proyectos' => 'tmp_proyectos#create'
  # match '/tmp_proyectos/:id' => 'tmp_proyectos#update'

  scope 'solicitud', controller: 'tmp_proyectos' do
    match 'nueva', action: 'new', as: :nueva_solicitud
    match 'crear', action: 'create', as: :crear_solicitud
    match 'editar/:id', action: 'edit', as: :editar_solicitud
    match 'eliminar/:id', action: 'destroy', as: :eliminar_solicitud
    post 'modificar/:id', action: 'update', as: :modificar_solicitud
    match 'aprobar/:id', action: 'aprobar', as: :aprobar_solicitud
  end

  scope 'proyecto', controller: 'proyectos' do
    match 'nuevo', action: 'new'
    match 'editar/:id', action: 'edit', as: :editar_proyecto
    match 'eliminar/:id', action: 'destroy', as: :eliminar_proyecto
    scope 'actividad', controller: 'actividades' do
      post 'evaluar/:id', action: 'evaluar', as: :evaluar_actividad
      match ':id/:actividad', action: 'index'
      match 'eliminar/:id/:actividad', action: 'destroy'
      match ':id/nueva-tarea/:actividad', action: 'nueva_tarea'
    end
  end

  scope 'actividad', controller: 'actividades' do
    match 'editar/:id', action: 'edit', as: :editar_actividad
  end
end

app/views/layouts/_head_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">TrazApp</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Usuarios", usuarios_path  %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proyectos <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Activos", '/activos'  %></li>
            <li><%= link_to "Solicitudes", '/solicitudes'  %></li>
          </ul>
        </li>
        <li><%= link_to "Reportes", '/reportes'  %></li>
        <li><%= link_to 'Configuraciones', '/configuraciones' %></li>
      </ul>
      <%= render partial: 'layouts/logged_info' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_logged_info.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-user"></span> <%= current_user.username %> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="<%= edit_usuario_path(current_user) %>"> <span class="glyphicon glyphicon-edit"></span> Editar Perfil</a></li>
      <li class="divider"></li>
      <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </li>
</ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TrazApp</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu message-dropdown">
          <li class="message-preview">
            <a href="#">
              <div class="media">
                <span class="pull-left">
                  <img class="media-object" src="http://placehold.it/50x50" alt="">
                </span>
                <div class="media-body">
                  <h5 class="media-heading"><strong><%= current_user.username %></strong>
                  </h5>
                  <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer a las 4:32 PM</p>
                  <p>Ingreso al sistema</p>
                </div>
              </div>
            </a>
          </li>
          <li class="message-preview">
            <a href="#">
              <div class="media">
                <span class="pull-left">
                  <img class="media-object" src="http://placehold.it/50x50" alt="">
                </span>
                <div class="media-body">
                  <h5 class="media-heading"><strong><%= current_user.username %></strong>
                  </h5>
                  <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer a las 4:32 PM</p>
                  <p>Desconectado del sistema</p>
                </div>
              </div>
            </a>
          </li>
          <li class="message-preview">
            <a href="#">
              <div class="media">
                <span class="pull-left">
                  <img class="media-object" src="http://placehold.it/50x50" alt="">
                </span>
                <div class="media-body">
                  <h5 class="media-heading"><strong><%= current_user.username %></strong>
                  </h5>
                  <p class="small text-muted"><i class="fa fa-clock-o"></i> Ayer a las 4:32 PM</p>
                  <p>Ingreso al sistema</p>
                </div>
              </div>
            </a>
          </li>
          <li class="message-footer">
            <a href="#">Leer todos los mensajes</a>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu alert-dropdown">
          <li>
            <a href="#">Solicitudes <span class="label label-default">3 Pendientes</span></a>
          </li>
          <li>
            <a href="#">Proyectos <span class="label label-primary">0 Aprobados</span></a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#">Ver todas</a>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.username %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <a href="<%= edit_usuario_path(current_user) %>"><i class="fa fa-fw fa-user"></i> Perfil</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-fw fa-gear"></i> Opciones</a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
          </li>
        </ul>
      </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li class="active">
            <a href="/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
        </li>
        <li>
            <a href="<%= usuarios_path %>"><i class="fa fa-fw fa fa-users"></i> Usuarios</a>
        </li>
        <li>
            <a href="<%= reportes_url %>"><i class="fa fa-fw fa-table"></i> Reportes</a>
        </li>
        <li>
            <a href="<%= solicitudes_url %>"><i class="fa fa-fw fa-edit"></i> Solicitudes</a>
        </li>

        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#estados"><i class="fa fa-fw fa-file"></i> Proyectos <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="estados" class="collapse">
                <li>
                    <a href="<%= proyectos_url %>">Activos</a>
                </li>
                <li>
                    <a href="#">Finalizados</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="<%= configuraciones_url %>"><i class="fa fa-fw fa-wrench"></i> Configuraciones</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrazApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "bootstrap-filestyle.min.js" %>
  </head>
  <body>
    <div id="wrapper">
      <%# render partial: 'layouts/head_bar' %>
      <%= render partial: 'layouts/navigation' %>
      <div id="page-wrapper">
        <%= flash_messages %>

        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <h1 class="page-header">
                <%= yield(:name) %> <small><%= yield(:description) %></small>
              </h1>
              <ol class="breadcrumb">
                <li class="active">
                  <%= yield(:breadcrumbs) %>
                </li>
              </ol>
            </div>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      $(function(){
        App.formsValidator();
      });
    </script>
  </body>
</html>

app/views/layouts/alumno.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrazApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">TrazApp</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Mi proyecto", '#'  %></li>
          </ul>
          <%= render partial: 'layouts/logged_info' %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= flash_messages %>

    <%= yield %>

    <script type="text/javascript">
      $(function(){
        App.formsValidator();
      });
    </script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TrazApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body id="home">
    <%= yield %>

    <script type="text/javascript">
      $(function(){
        App.init();
      });
    </script>
  </body>


</html>